name: nlaabo
description: "nlaabo- Football match organizer and team connector app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.0
  crypto: ^3.0.3
  bcrypt: ^1.1.3
  provider: ^6.1.2
  go_router: ^16.2.4
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.1.2
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  logger: ^2.4.0
  logging: ^1.2.0
  flutter_driver:
    sdk: flutter
  vm_service: ^14.2.1
  flutter_cache_manager: ^3.3.1
  image: ^4.1.3
  flutter_image_compress: ^2.1.0
  permission_handler: ^12.0.1
  path: any
  http_parser: any
  characters: 1.4.0
  material_color_utilities: 0.11.1
  meta: ^1.16.0
  intl_phone_number_input: ^0.7.5
  path_provider: any
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  flutter_screenutil: ^5.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/translations/en.json
    - assets/translations/fr.json
    - assets/translations/ar.json
    - assets/icons/logo_16.png
    - assets/icons/logo_32.png
    - assets/icons/logo_64.png
    - assets/icons/logo_128.png
    - assets/icons/logo_256.png
    - assets/icons/logo_512.png
    - assets/icons/logo_1024.png
    - assets/icons/logo.png

flutter_launcher_icons:
  image_path: "assets/icons/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21

  flavors:
    dev:
      image_path: "assets/icons/app_icon_dev.png"
      android: true
      ios: true
      remove_alpha_ios: true
      min_sdk_android: 21
      adaptive_icon_background: "#00FF00"

    staging:
      image_path: "assets/icons/app_icon_staging.png"
      android: true
      ios: true
      remove_alpha_ios: true
      min_sdk_android: 21
      adaptive_icon_background: "#FFFF00"

    prod:
      image_path: "assets/icons/app_icon.png"
      android: true
      ios: true
      remove_alpha_ios: true
      min_sdk_android: 21
      adaptive_icon_background: "#FF0000"
